### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [Matthewrsun/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - not counting keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- I would recommend organizing the images in a folder/subfolders to keep the repo more organized as there will be a lot of images for all lab reports.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Matthewrsun** [comment]
Hi, I was wondering how to put my images into a folder. When I do so, I can't access them from the markdown file anymore. I attached a picture of what my directory and workspace looks like.
![image](https://user-images.githubusercontent.com/95991612/151121856-c57f8dab-a079-4838-8816-43ff4087cc96.png)

**Comment by Matthewrsun** [comment]
Ok, I have added a section about counting keystrokes and put my pictures in a subfolder. I have also submitted a regrade request on Gradescope.

**Comment by nouryehia** [comment]
Sorry for the late reply. Glad you figured it out! Grade should be adjusted now!
